Add `krillta` package
NLnetLabs/krill pull request #1006
Opened 2023-01-26 15:30 UTC by ximon18

2023-02-09 15:54 UTC, ximon18 commented
I've marked this as ready for review because the [Packaging workflow run succeeded](https://github.com/NLnetLabs/krill/actions/runs/4135043229). The CI workflow appears to be failing for reasons unrelated to this PR.

2023-02-21 11:18 UTC, timbru requested changes

2023-02-21 11:18 UTC, timbru commented on doc/krillta.1
> +For more information visit https://rpki.readthedocs.io/en/latest/krill/trust-anchor.html.
The first paragraph is not that interesting to TA users - which would be power users - and the documentation link is wrong. I suggest:

The krillta tool is used for managing a Krill based RPKI Trust Anchor.

For more information visit https://krill.docs.nlnetlabs.nl/en/latest/trust-anchor.html

2023-02-21 11:18 UTC, timbru commented on pkg/debian/description-krillta.txt
> +For more information visit https://rpki.readthedocs.io/en/latest/krill/trust-anchor.html.
as above

2023-02-21 11:25 UTC, timbru approved these changes

2023-03-07 14:12 UTC, timbru approved these changes

2023-03-07 14:13 UTC, merged